version: '3.1'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    environment:
      MYSQL_ROOT_PASSWORD: web1

  php:
    image: alexkutzke/php-mysqli
    links:
      - db
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
