/**
 * @author Felipe Augusto Vieira Zampa
 * @author Bruna da Silva Lins
 * Lista 8 exercicio 4
 */
package T08_Ex4;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class SistemaAcademico extends javax.swing.JFrame {
    
    private static Professor professores[];
    private static int quantidadeProfessor = 0;
    private static Aluno alunos[];
    private static int quantidadeAluno = 0;

    /**
     * Creates new form SistemaAcademico
     */
    public SistemaAcademico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JTabbedPane();
        tabCadastrarAluno = new javax.swing.JPanel();
        labelCadastrarAlunoNome = new javax.swing.JLabel();
        labelCadastrarAlunoIdade = new javax.swing.JLabel();
        labelCadastrarAlunoEndereço = new javax.swing.JLabel();
        labelCadastrarAlunoMatricula = new javax.swing.JLabel();
        labelCadastrarAlunoCurso = new javax.swing.JLabel();
        labelCadastrarAlunoPeriodo = new javax.swing.JLabel();
        textCadastrarAlunoCurso = new javax.swing.JTextField();
        textCadastrarAlunoMatricula = new javax.swing.JTextField();
        textCadastrarAlunoPeriodo = new javax.swing.JTextField();
        textCadastrarAlunoNome = new javax.swing.JTextField();
        textCadastrarAlunoIdade = new javax.swing.JTextField();
        textCadastrarAlunoEndereço = new javax.swing.JTextField();
        botaoCadastrarAluno = new javax.swing.JButton();
        tabMatricularAluno = new javax.swing.JPanel();
        textMatricularAlunoNome = new javax.swing.JTextField();
        labelMatricularAlunoNome = new javax.swing.JLabel();
        botaoMatricularAluno = new javax.swing.JButton();
        labelMatricularAlunoDisciplina = new javax.swing.JLabel();
        textMatricularAlunoDisciplina = new javax.swing.JTextField();
        tabExcluirAluno = new javax.swing.JPanel();
        textExcluirAlunoNome = new javax.swing.JTextField();
        labelExcluirAlunoNome = new javax.swing.JLabel();
        botaoExcluirAluno = new javax.swing.JButton();
        tabExcluirMatriculaAluno = new javax.swing.JPanel();
        labelExcluirMatriculaAlunoDisciplina = new javax.swing.JLabel();
        textExcluirMatriculaAlunoDisciplina = new javax.swing.JTextField();
        textExcluirMatriculaAlunoNome = new javax.swing.JTextField();
        labelExcluirMatriculaAlunoNome = new javax.swing.JLabel();
        botaoExcluirMatriculaAluno = new javax.swing.JButton();
        tabImprimirAluno = new javax.swing.JPanel();
        botaoImprimeAlunos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoAreaImprime = new javax.swing.JTextArea();
        tabCadastrarProfessor = new javax.swing.JPanel();
        labelCadastrarProfessorNome = new javax.swing.JLabel();
        textCadastrarProfessorNome = new javax.swing.JTextField();
        labelCadastrarProfessorIdade = new javax.swing.JLabel();
        textCadastrarProfessorIdade = new javax.swing.JTextField();
        labelCadastrarProfessorEndereço = new javax.swing.JLabel();
        textCadastrarProfessorEndereço = new javax.swing.JTextField();
        botaoCadastrarProfessor = new javax.swing.JButton();
        tabMatricularProfessor = new javax.swing.JPanel();
        labelMatricularProfessorDisciplina = new javax.swing.JLabel();
        textMatricularProfessorDisciplina = new javax.swing.JTextField();
        textMatricularProfessorNome = new javax.swing.JTextField();
        labelMatricularProfessorNome = new javax.swing.JLabel();
        botaoMatricularProfessor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        labelCadastrarAlunoNome.setText("Nome:");

        labelCadastrarAlunoIdade.setText("Idade:");

        labelCadastrarAlunoEndereço.setText("Endereço:");

        labelCadastrarAlunoMatricula.setText("Matrícula:");

        labelCadastrarAlunoCurso.setText("Curso:");

        labelCadastrarAlunoPeriodo.setText("Período:");

        botaoCadastrarAluno.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        botaoCadastrarAluno.setText("Cadastrar Aluno");
        botaoCadastrarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarAlunoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabCadastrarAlunoLayout = new javax.swing.GroupLayout(tabCadastrarAluno);
        tabCadastrarAluno.setLayout(tabCadastrarAlunoLayout);
        tabCadastrarAlunoLayout.setHorizontalGroup(
            tabCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCadastrarAlunoLayout.createSequentialGroup()
                .addGroup(tabCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabCadastrarAlunoLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(tabCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(tabCadastrarAlunoLayout.createSequentialGroup()
                                .addGroup(tabCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(tabCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(tabCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelCadastrarAlunoEndereço)
                                            .addComponent(labelCadastrarAlunoPeriodo, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addComponent(labelCadastrarAlunoCurso, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(labelCadastrarAlunoMatricula, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(tabCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(tabCadastrarAlunoLayout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(tabCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textCadastrarAlunoMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textCadastrarAlunoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(tabCadastrarAlunoLayout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addGroup(tabCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(textCadastrarAlunoIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(textCadastrarAlunoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(textCadastrarAlunoEndereço, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(textCadastrarAlunoPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(tabCadastrarAlunoLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(tabCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelCadastrarAlunoNome, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelCadastrarAlunoIdade, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(457, 457, 457))))
                    .addGroup(tabCadastrarAlunoLayout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(botaoCadastrarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tabCadastrarAlunoLayout.setVerticalGroup(
            tabCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCadastrarAlunoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(tabCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textCadastrarAlunoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCadastrarAlunoNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tabCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textCadastrarAlunoIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCadastrarAlunoIdade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tabCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textCadastrarAlunoEndereço, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCadastrarAlunoEndereço))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tabCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textCadastrarAlunoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCadastrarAlunoCurso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tabCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textCadastrarAlunoMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCadastrarAlunoMatricula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tabCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textCadastrarAlunoPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCadastrarAlunoPeriodo))
                .addGap(38, 38, 38)
                .addComponent(botaoCadastrarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Menu.addTab("Cadastrar Aluno", tabCadastrarAluno);

        labelMatricularAlunoNome.setText("Nome:");

        botaoMatricularAluno.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        botaoMatricularAluno.setText("Matricular Aluno");
        botaoMatricularAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMatricularAlunoActionPerformed(evt);
            }
        });

        labelMatricularAlunoDisciplina.setText("Disciplina:");

        javax.swing.GroupLayout tabMatricularAlunoLayout = new javax.swing.GroupLayout(tabMatricularAluno);
        tabMatricularAluno.setLayout(tabMatricularAlunoLayout);
        tabMatricularAlunoLayout.setHorizontalGroup(
            tabMatricularAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabMatricularAlunoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botaoMatricularAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(295, 295, 295))
            .addGroup(tabMatricularAlunoLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(tabMatricularAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tabMatricularAlunoLayout.createSequentialGroup()
                        .addComponent(labelMatricularAlunoDisciplina)
                        .addGap(18, 18, 18)
                        .addComponent(textMatricularAlunoDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tabMatricularAlunoLayout.createSequentialGroup()
                        .addComponent(labelMatricularAlunoNome)
                        .addGap(18, 18, 18)
                        .addComponent(textMatricularAlunoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tabMatricularAlunoLayout.setVerticalGroup(
            tabMatricularAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabMatricularAlunoLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(tabMatricularAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textMatricularAlunoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMatricularAlunoNome))
                .addGap(18, 18, 18)
                .addGroup(tabMatricularAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textMatricularAlunoDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMatricularAlunoDisciplina))
                .addGap(29, 29, 29)
                .addComponent(botaoMatricularAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Menu.addTab("Matricular Aluno", tabMatricularAluno);

        textExcluirAlunoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textExcluirAlunoNomeActionPerformed(evt);
            }
        });

        labelExcluirAlunoNome.setText("Nome:");

        botaoExcluirAluno.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        botaoExcluirAluno.setText("Excluir Aluno");
        botaoExcluirAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirAlunoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabExcluirAlunoLayout = new javax.swing.GroupLayout(tabExcluirAluno);
        tabExcluirAluno.setLayout(tabExcluirAlunoLayout);
        tabExcluirAlunoLayout.setHorizontalGroup(
            tabExcluirAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabExcluirAlunoLayout.createSequentialGroup()
                .addGroup(tabExcluirAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabExcluirAlunoLayout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(botaoExcluirAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tabExcluirAlunoLayout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addGroup(tabExcluirAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabExcluirAlunoLayout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(textExcluirAlunoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelExcluirAlunoNome))))
                .addGap(182, 182, 182))
        );
        tabExcluirAlunoLayout.setVerticalGroup(
            tabExcluirAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabExcluirAlunoLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(tabExcluirAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textExcluirAlunoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelExcluirAlunoNome))
                .addGap(34, 34, 34)
                .addComponent(botaoExcluirAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Menu.addTab("Excluir Aluno", tabExcluirAluno);

        labelExcluirMatriculaAlunoDisciplina.setText("Disciplina:");

        labelExcluirMatriculaAlunoNome.setText("Nome:");

        botaoExcluirMatriculaAluno.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        botaoExcluirMatriculaAluno.setText("Cancelar Matrícula");
        botaoExcluirMatriculaAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirMatriculaAlunoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabExcluirMatriculaAlunoLayout = new javax.swing.GroupLayout(tabExcluirMatriculaAluno);
        tabExcluirMatriculaAluno.setLayout(tabExcluirMatriculaAlunoLayout);
        tabExcluirMatriculaAlunoLayout.setHorizontalGroup(
            tabExcluirMatriculaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabExcluirMatriculaAlunoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botaoExcluirMatriculaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(295, 295, 295))
            .addGroup(tabExcluirMatriculaAlunoLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(tabExcluirMatriculaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tabExcluirMatriculaAlunoLayout.createSequentialGroup()
                        .addComponent(labelExcluirMatriculaAlunoDisciplina)
                        .addGap(18, 18, 18)
                        .addComponent(textExcluirMatriculaAlunoDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tabExcluirMatriculaAlunoLayout.createSequentialGroup()
                        .addComponent(labelExcluirMatriculaAlunoNome)
                        .addGap(18, 18, 18)
                        .addComponent(textExcluirMatriculaAlunoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tabExcluirMatriculaAlunoLayout.setVerticalGroup(
            tabExcluirMatriculaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabExcluirMatriculaAlunoLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(tabExcluirMatriculaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textExcluirMatriculaAlunoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelExcluirMatriculaAlunoNome))
                .addGap(18, 18, 18)
                .addGroup(tabExcluirMatriculaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textExcluirMatriculaAlunoDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelExcluirMatriculaAlunoDisciplina))
                .addGap(29, 29, 29)
                .addComponent(botaoExcluirMatriculaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Menu.addTab("Excluir Matricula Aluno", tabExcluirMatriculaAluno);

        botaoImprimeAlunos.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        botaoImprimeAlunos.setText("Imprimir Alunos");
        botaoImprimeAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoImprimeAlunosActionPerformed(evt);
            }
        });

        textoAreaImprime.setColumns(20);
        textoAreaImprime.setRows(5);
        jScrollPane1.setViewportView(textoAreaImprime);

        javax.swing.GroupLayout tabImprimirAlunoLayout = new javax.swing.GroupLayout(tabImprimirAluno);
        tabImprimirAluno.setLayout(tabImprimirAlunoLayout);
        tabImprimirAlunoLayout.setHorizontalGroup(
            tabImprimirAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabImprimirAlunoLayout.createSequentialGroup()
                .addGap(289, 289, 289)
                .addComponent(botaoImprimeAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(tabImprimirAlunoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        tabImprimirAlunoLayout.setVerticalGroup(
            tabImprimirAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabImprimirAlunoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(botaoImprimeAlunos)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                .addContainerGap())
        );

        Menu.addTab("Imprimir Alunos", tabImprimirAluno);

        labelCadastrarProfessorNome.setText("Nome:");

        textCadastrarProfessorNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCadastrarProfessorNomeActionPerformed(evt);
            }
        });

        labelCadastrarProfessorIdade.setText("Idade:");

        labelCadastrarProfessorEndereço.setText("Endereço:");

        textCadastrarProfessorEndereço.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCadastrarProfessorEndereçoActionPerformed(evt);
            }
        });

        botaoCadastrarProfessor.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        botaoCadastrarProfessor.setText("Cadastrar Professor");
        botaoCadastrarProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarProfessorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabCadastrarProfessorLayout = new javax.swing.GroupLayout(tabCadastrarProfessor);
        tabCadastrarProfessor.setLayout(tabCadastrarProfessorLayout);
        tabCadastrarProfessorLayout.setHorizontalGroup(
            tabCadastrarProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCadastrarProfessorLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addGroup(tabCadastrarProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabCadastrarProfessorLayout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(botaoCadastrarProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tabCadastrarProfessorLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(tabCadastrarProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCadastrarProfessorNome, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelCadastrarProfessorIdade, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(tabCadastrarProfessorLayout.createSequentialGroup()
                        .addComponent(labelCadastrarProfessorEndereço)
                        .addGap(18, 18, 18)
                        .addGroup(tabCadastrarProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabCadastrarProfessorLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(tabCadastrarProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textCadastrarProfessorIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textCadastrarProfessorNome, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(textCadastrarProfessorEndereço, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        tabCadastrarProfessorLayout.setVerticalGroup(
            tabCadastrarProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCadastrarProfessorLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(tabCadastrarProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textCadastrarProfessorNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCadastrarProfessorNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tabCadastrarProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textCadastrarProfessorIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCadastrarProfessorIdade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tabCadastrarProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textCadastrarProfessorEndereço, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCadastrarProfessorEndereço))
                .addGap(26, 26, 26)
                .addComponent(botaoCadastrarProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        Menu.addTab("Cadastrar Professor", tabCadastrarProfessor);

        labelMatricularProfessorDisciplina.setText("Disciplina:");

        labelMatricularProfessorNome.setText("Nome:");

        botaoMatricularProfessor.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        botaoMatricularProfessor.setText("Matricular Professor");
        botaoMatricularProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMatricularProfessorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabMatricularProfessorLayout = new javax.swing.GroupLayout(tabMatricularProfessor);
        tabMatricularProfessor.setLayout(tabMatricularProfessorLayout);
        tabMatricularProfessorLayout.setHorizontalGroup(
            tabMatricularProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabMatricularProfessorLayout.createSequentialGroup()
                .addGroup(tabMatricularProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabMatricularProfessorLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(tabMatricularProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(tabMatricularProfessorLayout.createSequentialGroup()
                                .addComponent(labelMatricularProfessorDisciplina)
                                .addGap(18, 18, 18)
                                .addComponent(textMatricularProfessorDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tabMatricularProfessorLayout.createSequentialGroup()
                                .addComponent(labelMatricularProfessorNome)
                                .addGap(18, 18, 18)
                                .addComponent(textMatricularProfessorNome, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(tabMatricularProfessorLayout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(botaoMatricularProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tabMatricularProfessorLayout.setVerticalGroup(
            tabMatricularProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabMatricularProfessorLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(tabMatricularProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textMatricularProfessorNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMatricularProfessorNome))
                .addGap(18, 18, 18)
                .addGroup(tabMatricularProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textMatricularProfessorDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMatricularProfessorDisciplina))
                .addGap(29, 29, 29)
                .addComponent(botaoMatricularProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Menu.addTab("Matricular Professor", tabMatricularProfessor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCadastrarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarAlunoActionPerformed
        String nome = textCadastrarAlunoNome.getText();
        int idade = Integer.parseInt(textCadastrarAlunoIdade.getText());
        String endereco = textCadastrarAlunoEndereço.getText();
        String matricula = textCadastrarAlunoMatricula.getText();
        String curso = textCadastrarAlunoCurso.getText();
        int periodo = Integer.parseInt(textCadastrarAlunoPeriodo.getText());
        int quantidadeDisciplinasPermitidas = 0;
        
        alunos[quantidadeAluno] = new Aluno(nome, idade, endereco, matricula, curso, periodo, quantidadeDisciplinasPermitidas);
        quantidadeAluno++;
        
        JFrame jFrame = new JFrame();
        JOptionPane.showMessageDialog(jFrame, "Aluno Cadastrado com sucesso!");
    }//GEN-LAST:event_botaoCadastrarAlunoActionPerformed

    private void botaoMatricularAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMatricularAlunoActionPerformed
        JFrame jFrame = new JFrame();
        String nome = textMatricularAlunoNome.getText();
        String nomeDisciplina = textMatricularAlunoDisciplina.getText();
        Disciplina disciplina = new Disciplina(nomeDisciplina);
        
        int i = 0;
        while(i < quantidadeAluno && !nome.equals(alunos[i].getNome())) {
            i++;
        }

        if (i < quantidadeAluno) {
            if (alunos[i].getquantidadeDisciplinasMatriculadas() == 0) {
                boolean condicao = true;
                while(condicao) {
                    try {
                        String getQuantidadeDisciplinas = JOptionPane.showInputDialog(jFrame, 
                                                                "Quantas disciplinas o aluno deve ser matriculado?");
                        int quantidadeDisciplinas = Integer.parseInt(getQuantidadeDisciplinas);

                        alunos[i].setQuantidadeDisciplinasPermitidas(quantidadeDisciplinas);
                        condicao = false;
                    } catch(NumberFormatException nfe) {
                        JOptionPane.showMessageDialog(null,"A quantidade deve ser numérica!", "Erro: ", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }

            String informe = alunos[i].fazMatricula(disciplina);
            JOptionPane.showMessageDialog(jFrame, informe);
        } else {
            JOptionPane.showMessageDialog(jFrame, "Aluno não encontrado.");
        }
    }//GEN-LAST:event_botaoMatricularAlunoActionPerformed

    private void textExcluirAlunoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textExcluirAlunoNomeActionPerformed

    }//GEN-LAST:event_textExcluirAlunoNomeActionPerformed

    private void botaoExcluirAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirAlunoActionPerformed
        JFrame jFrame = new JFrame();
        String nome = textExcluirAlunoNome.getText();
        
        int i = 0;
        while(i < quantidadeAluno && !nome.equals(alunos[i].getNome())) {
            i++;
        }
        
        if (i < quantidadeAluno) {
            for (int k = i; k < quantidadeAluno; k++) {
                alunos[k] = alunos[k+1];
            }
            
            quantidadeAluno--;
            
            JOptionPane.showMessageDialog(jFrame, "Aluno excluído com sucesso!");
        } else {
            JOptionPane.showMessageDialog(jFrame, "O aluno não foi encontrado.");
        }
    }//GEN-LAST:event_botaoExcluirAlunoActionPerformed

    private void botaoExcluirMatriculaAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirMatriculaAlunoActionPerformed
        JFrame jFrame = new JFrame();
        String nome = textExcluirMatriculaAlunoNome.getText();
        String disciplina = textExcluirMatriculaAlunoDisciplina.getText();
        
        int i = 0;
        while(i < quantidadeAluno && !nome.equals(alunos[i].getNome())) {
            i++;
        }

        if (i < quantidadeAluno) {
            String informe = alunos[i].cancelarMatricula(disciplina);
            JOptionPane.showMessageDialog(jFrame, informe);
        } else {
            JOptionPane.showMessageDialog(jFrame, "O aluno não foi encontrado.");
        }

    }//GEN-LAST:event_botaoExcluirMatriculaAlunoActionPerformed

    private void botaoImprimeAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoImprimeAlunosActionPerformed
        String aluno = "";
        
        for (int i = 0; i < quantidadeAluno; i++) {
            aluno += alunos[i].imprime();
            textoAreaImprime.setText(aluno);
        }
    }//GEN-LAST:event_botaoImprimeAlunosActionPerformed

    private void textCadastrarProfessorEndereçoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCadastrarProfessorEndereçoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCadastrarProfessorEndereçoActionPerformed

    private void botaoCadastrarProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarProfessorActionPerformed
        String nome = textCadastrarProfessorNome.getText();
        int idade = Integer.parseInt(textCadastrarProfessorIdade.getText());
        String endereco = textCadastrarProfessorEndereço.getText();
        int quantidadeDisciplinasMinistradas = 0;
        
        professores[quantidadeProfessor] = new Professor(nome, idade, endereco, quantidadeDisciplinasMinistradas);
        quantidadeProfessor++;
        
        JFrame jFrame = new JFrame();
        JOptionPane.showMessageDialog(jFrame, "Professor Cadastrado com sucesso!");
    }//GEN-LAST:event_botaoCadastrarProfessorActionPerformed

    private void botaoMatricularProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMatricularProfessorActionPerformed
        JFrame jFrame = new JFrame();
        String nome = textMatricularProfessorNome.getText();
        String nomeDisciplina = textMatricularProfessorDisciplina.getText();
        Disciplina disciplina = new Disciplina(nomeDisciplina);
        
        int i = 0;
        while(i < quantidadeProfessor && !nome.equals(professores[i].getNome())) {
            i++;
        }

        if (i < quantidadeProfessor) {
            if (professores[i].getquantidadeDisciplinasMatriculadas() == 0) {
                boolean condicao = true;
                while(condicao) {
                    try {
                        String getQuantidadeDisciplinas = JOptionPane.showInputDialog(jFrame, 
                                                                "Quantas disciplinas o professor deve ministrar?");
                        int quantidadeDisciplinas = Integer.parseInt(getQuantidadeDisciplinas);

                        professores[i].setQuantidadeDisciplinasMatriculadas(quantidadeDisciplinas);
                        condicao = false;
                    } catch(NumberFormatException nfe) {
                        JOptionPane.showMessageDialog(null,"A quantidade deve ser numérica!", "Erro: ", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }

            String informe = professores[i].fazMatricula(disciplina);
            JOptionPane.showMessageDialog(jFrame, informe);
        } else {
            JOptionPane.showMessageDialog(jFrame, "Professor não encontrado.");
        }
    }//GEN-LAST:event_botaoMatricularProfessorActionPerformed

    private void textCadastrarProfessorNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCadastrarProfessorNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCadastrarProfessorNomeActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        boolean condicao = true;
        while(condicao) {
            try {
                int quantidadeTotalProfessores, quantidadeTotalAlunos, i;

                JFrame jFrame = new JFrame();
                String getQuantidadeTotalProfessores = JOptionPane.showInputDialog(jFrame, 
                                                        "Quantos professores serão cadastrados?");
                quantidadeTotalProfessores = Integer.parseInt(getQuantidadeTotalProfessores);

                String getQuantidadeTotalAlunos = JOptionPane.showInputDialog(jFrame, 
                                                    "Quantos alunos serão cadastrados?");
                quantidadeTotalAlunos = Integer.parseInt(getQuantidadeTotalAlunos);

                professores = new Professor[quantidadeTotalProfessores];
                alunos = new Aluno[quantidadeTotalAlunos];
                
                condicao = false;
            } catch(NumberFormatException ex) {
                JOptionPane.showMessageDialog(null,"A quantidade deve ser numérica!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemaAcademico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemaAcademico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemaAcademico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemaAcademico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemaAcademico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Menu;
    private javax.swing.JButton botaoCadastrarAluno;
    private javax.swing.JButton botaoCadastrarProfessor;
    private javax.swing.JButton botaoExcluirAluno;
    private javax.swing.JButton botaoExcluirMatriculaAluno;
    private javax.swing.JButton botaoImprimeAlunos;
    private javax.swing.JButton botaoMatricularAluno;
    private javax.swing.JButton botaoMatricularProfessor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCadastrarAlunoCurso;
    private javax.swing.JLabel labelCadastrarAlunoEndereço;
    private javax.swing.JLabel labelCadastrarAlunoIdade;
    private javax.swing.JLabel labelCadastrarAlunoMatricula;
    private javax.swing.JLabel labelCadastrarAlunoNome;
    private javax.swing.JLabel labelCadastrarAlunoPeriodo;
    private javax.swing.JLabel labelCadastrarProfessorEndereço;
    private javax.swing.JLabel labelCadastrarProfessorIdade;
    private javax.swing.JLabel labelCadastrarProfessorNome;
    private javax.swing.JLabel labelExcluirAlunoNome;
    private javax.swing.JLabel labelExcluirMatriculaAlunoDisciplina;
    private javax.swing.JLabel labelExcluirMatriculaAlunoNome;
    private javax.swing.JLabel labelMatricularAlunoDisciplina;
    private javax.swing.JLabel labelMatricularAlunoNome;
    private javax.swing.JLabel labelMatricularProfessorDisciplina;
    private javax.swing.JLabel labelMatricularProfessorNome;
    private javax.swing.JPanel tabCadastrarAluno;
    private javax.swing.JPanel tabCadastrarProfessor;
    private javax.swing.JPanel tabExcluirAluno;
    private javax.swing.JPanel tabExcluirMatriculaAluno;
    private javax.swing.JPanel tabImprimirAluno;
    private javax.swing.JPanel tabMatricularAluno;
    private javax.swing.JPanel tabMatricularProfessor;
    private javax.swing.JTextField textCadastrarAlunoCurso;
    private javax.swing.JTextField textCadastrarAlunoEndereço;
    private javax.swing.JTextField textCadastrarAlunoIdade;
    private javax.swing.JTextField textCadastrarAlunoMatricula;
    private javax.swing.JTextField textCadastrarAlunoNome;
    private javax.swing.JTextField textCadastrarAlunoPeriodo;
    private javax.swing.JTextField textCadastrarProfessorEndereço;
    private javax.swing.JTextField textCadastrarProfessorIdade;
    private javax.swing.JTextField textCadastrarProfessorNome;
    private javax.swing.JTextField textExcluirAlunoNome;
    private javax.swing.JTextField textExcluirMatriculaAlunoDisciplina;
    private javax.swing.JTextField textExcluirMatriculaAlunoNome;
    private javax.swing.JTextField textMatricularAlunoDisciplina;
    private javax.swing.JTextField textMatricularAlunoNome;
    private javax.swing.JTextField textMatricularProfessorDisciplina;
    private javax.swing.JTextField textMatricularProfessorNome;
    private javax.swing.JTextArea textoAreaImprime;
    // End of variables declaration//GEN-END:variables
}