services:
 postgres:
  image: postgres
  ports:
   - 5432:5432
  environment:
   - POSTGRES_DEFAULT_USER=admin
   - POSTGRES_DEFAULT_PASSWORD=admin
 rabbitmq:
  image: rabbitmq:3-management
  container_name: rabbitmq_management
  restart: always
  ports:
   - 5672:5672
   - 15672:15672 
  volumes:
   - ./data:/var/lib/postgresql/data	

  environment:
   - RABBITMQ_DEFAULT_USER=guest
   - RABBITMQ_DEFAULT_PASS=guest


   
